# Generated by Django 4.2.29 on 2026-04-05 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(help_text='Например синтаксис, циклы, функции', max_length=100, verbose_name='Тема')),
                ('question', models.TextField(help_text='Текст задания', verbose_name='Вопрос')),
                ('answer', models.CharField(help_text='Правильный ответ', max_length=100, verbose_name='Ответ')),
                ('difficulty', models.CharField(choices=[('easy', 'Легко'), ('medium', 'Средне'), ('hard', 'Сложно')], default='easy', max_length=10, verbose_name='Сложность')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Задание',
                'verbose_name_plural': 'Задания',
                'ordering': ['topic', 'difficulty'],
            },
        ),
    ]
